os: linux
language: node_js
addons:
  chrome: stable
before_install:
  - npm install yarn -g
cache:
  yarn: true
notifications:
  email: false
node_js:
  - "12"
  - "11"
  - "10"

script: echo "Running tests against $(node -v) ..."

jobs:
  include:
    - stage: test
      script:
        - yarn commitlint-travis
    - script:
        - yarn build:prod
        - yarn test:once
        - cat ./coverage/core/lcov.info | ./node_modules/coveralls/bin/coveralls.js
    - stage: deploy
      node_js: 12
      script: skip
      deploy:
        provider: script
        cleanup: true
        script:
          - yarn && yarn build:prod && yarn semantic-release

stages:
  - lint
  - test
  - name: deploy
    if: branch = master